# MySQL - Configuración de Producción
spring.datasource.url=jdbc:mysql://localhost:3306/contractflow?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
#en contractflow eso es nombre de la base de datos, preguntar por el localhost

spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Eso debo poner al final para que funcione